### ISSUE TITLE
Allow users to select their own timezone

### ISSUE THREAD

**Issue by chrisscastaneda** [brendanmurty/upcomingtasks#2]
love the app!   however i'm live in seattle (pacific standard time) and it looks like the tool defaults to the Australia/Sydney timezone, as such all my due dates are off by a day.  it doesn't look like there's a way to change this from inside of the app.
thx!

**Comment by brendanmurty** [comment]
This is now part of the just released [UpcomingTasks Pro account](http://brendan.murty.id.au/post/announcing-upcomingtasks-pro)!
